name: material_flutter_io19
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  firebase_ml_vision: ^0.7.0+2
  camera: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Libre Franklin
      fonts:
        - asset: fonts/LibreFranklin-Regular.ttf
          weight: 400
        - asset: fonts/LibreFranklin-Medium.ttf
          weight: 500
        - asset: fonts/LibreFranklin-SemiBold.ttf
          weight: 600
        - asset: fonts/LibreFranklin-Bold.ttf
          weight: 700
        - asset: fonts/LibreFranklin-ExtraBold.ttf
          weight: 900
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Light.ttf
          weight: 300
        - asset: fonts/Merriweather-Regular.ttf
          weight: 400
        - asset: fonts/Merriweather-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto Condensed
      fonts:
        - asset: fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
