name: web_benchmarks_framework
description: A framework for running flutter web benchmarks.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ">=1.6.0"
  logging: ">=0.11.4"
  process: ">=3.0.13"
  shelf: ">=0.7.5"
  shelf_static: ">=0.2.8"
  vm_service_client: ">=0.2.6+2"
  webkit_inspection_protocol: ">=0.7.3"
  yaml: ">=2.2.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
